import { useEffect } from 'react';
import {
  projectCaseStudies,
  projects,
  type CaseStudySection,
  type ContentRecord,
} from '@/data/roboticsPortfolioData';
import { CaseStudyLayout } from '@/components/case-study-layout';
import { SupportingMaterials } from '@/components/supporting-materials';
import { DeepLearningComparisonDiagram, SystemFlowDiagram } from '@/components/system-diagrams';
import NotFound from './not-found';

function Section({ section }: { section: CaseStudySection }) {
  return (
    <section>
      <h2 className="text-xl font-bold text-foreground mb-3 border-l-2 border-primary pl-4">
        {section.heading}
      </h2>
      <div className="space-y-3 pl-4">
        {section.paragraphs.filter(Boolean).map((paragraph) => (
          <p key={paragraph} className="text-muted-foreground leading-relaxed">
            {paragraph}
          </p>
        ))}
      </div>
    </section>
  );
}

function ProjectDiagram({ projectId }: { projectId: string }) {
  if (projectId === 'smart-manhole-monitoring') {
    return (
      <SystemFlowDiagram
        label="SYSTEM ARCHITECTURE"
        stages={[
          'Ultrasonic + Temperature Sensors',
          'Arduino Uno WiFi',
          'MQTT',
          'Raspberry Pi 5 + Python',
          'Monitoring + LED Alerts',
        ]}
      />
    );
  }

  if (projectId === 'inbody-meal-recommendation') {
    return (
      <section>
        <h2 className="text-xl font-bold text-foreground mb-4 border-l-2 border-primary pl-4">
          Paper Figures
        </h2>
        <div className="space-y-6 pl-4">
          <figure className="border border-border bg-card/30 p-4 sm:p-6">
            <a
              href="/projects/inbody-meal-recommendation-system-flow.webp"
              target="_blank"
              rel="noreferrer"
              aria-label="Open the meal recommendation system flowchart in full resolution"
              className="block focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary"
            >
              <img
                src="/projects/inbody-meal-recommendation-system-flow.webp"
                alt="Flowchart showing personal information and goals entering InBody analysis, nutrient calculation, food-database filtering, meal-plan matching, repetition checking, and a personalized three-meal plan."
                width={1513}
                height={1039}
                loading="lazy"
                decoding="async"
                className="w-full h-auto object-contain bg-white"
              />
            </a>
            <figcaption className="mt-3 text-sm text-muted-foreground leading-relaxed">
              Figure 1. Proposed workflow linking body information, nutritional requirements,
              food data, meal matching, and repetition checking.
            </figcaption>
          </figure>

          <figure className="border border-border bg-card/30 p-4 sm:p-6">
            <a
              href="/projects/inbody-meal-recommendation-10-day-results.webp"
              target="_blank"
              rel="noreferrer"
              aria-label="Open the ten-day meal recommendation results in full resolution"
              className="block focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary"
            >
              <img
                src="/projects/inbody-meal-recommendation-10-day-results.webp"
                alt="Ten-day table of simulated breakfast, lunch, dinner, carbohydrate, protein, fat, and calorie results generated by the meal-matching algorithm."
                width={2239}
                height={1205}
                loading="lazy"
                decoding="async"
                className="w-full h-auto object-contain bg-white"
              />
            </a>
            <figcaption className="mt-3 text-sm text-muted-foreground leading-relaxed">
              Figure 2. Ten-day sample from the 30-day synthetic-user simulation. Open the
              figure to inspect the full-resolution table.
            </figcaption>
          </figure>
        </div>
      </section>
    );
  }

  if (projectId === 'deep-learning-code-development') {
    return <DeepLearningComparisonDiagram />;
  }

  if (projectId === 'machine-learning-textbook-contribution') {
    return (
      <SystemFlowDiagram
        label="TEXTBOOK CONTRIBUTION WORKFLOW"
        stages={[
          'Data Processing Foundations',
          'Regression and ML Examples',
          'R/Python Testing',
          'Figures and Proofreading',
        ]}
      />
    );
  }

  return null;
}

function Technologies({ project }: { project: ContentRecord }) {
  if (!project.technologies?.length) return null;

  return (
    <section>
      <h2 className="text-xl font-bold text-foreground mb-3 border-l-2 border-primary pl-4">
        Technologies and Methods
      </h2>
      <ul className="flex flex-wrap gap-2 list-none pl-4">
        {project.technologies.map((technology) => (
          <li
            key={technology}
            className="px-2.5 py-1 text-xs font-mono text-foreground/80 bg-secondary border border-border"
          >
            {technology}
          </li>
        ))}
      </ul>
    </section>
  );
}

export default function ProjectDetail({ projectId }: { projectId: string }) {
  const project = projects.find((item) => item.id === projectId && item.visible);
  const caseStudy = projectCaseStudies[projectId];

  useEffect(() => {
    window.scrollTo(0, 0);
    if (project) {
      document.title = `${project.title} | Hyeonmin Cho`;
    }
    return () => {
      document.title = 'Hyeonmin Cho | Electrical & Electronics Engineering Portfolio';
    };
  }, [project]);

  if (!project || !caseStudy) return <NotFound />;

  const publicSections = caseStudy.sections.filter((section) =>
    section.paragraphs.some((paragraph) => Boolean(paragraph.trim())),
  );

  return (
    <CaseStudyLayout
      eyebrow={
        project.id === 'inbody-meal-recommendation'
          ? 'ACADEMIC PAPER'
          : project.id === 'machine-learning-textbook-contribution' ||
              project.id === 'deep-learning-code-development'
            ? 'TECHNICAL CONTRIBUTION'
            : 'ENGINEERING PROJECT'
      }
      title={project.title}
      originalTitle={project.originalTitle}
      meta={[project.role ?? '', project.organization ?? '', project.period ?? '', project.location ?? '']}
    >
      <div className="space-y-10">
        <section>
          <h2 className="text-xl font-bold text-foreground mb-3 border-l-2 border-primary pl-4">
            Project Overview
          </h2>
          <p className="pl-4 text-muted-foreground leading-relaxed">
            {project.detailedDescription ?? project.shortDescription}
          </p>
        </section>

        <ProjectDiagram projectId={project.id} />

        {publicSections.map((section) => (
          <Section key={section.heading} section={section} />
        ))}

        <Technologies project={project} />
        <SupportingMaterials record={project} />
      </div>
    </CaseStudyLayout>
  );
}
